apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stockertest
  name: stockertest
spec:
  containers:
  - image: talshor123/talshorrepo:0.2
    name: stockertest
    ports:
      - containerPort: 30001
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
